### ISSUE TITLE
"System.Exception: Invalid chunk header" when loading a map

### ISSUE THREAD

**Issue by MHeasell** [MHeasell/Mappy#7]
via bugsnag:

```
System.Exception: Invalid chunk header
   at TAUtil.Hpi.HpiArchive.Extract(FileInfo file, byte[] buffer) in C:\projects\mappy\TAUtil\TAUtil\Hpi\HpiArchive.cs:line 242
   at Mappy.Services.MapLoadingService.CreateFromHpi(string hpipath, string mappath, bool readOnly) in C:\projects\mappy\Mappy\Services\MapLoadingService.cs:line 91
   at Mappy.Services.Dispatcher.OpenFromHapi(string filename) in C:\projects\mappy\Mappy\Services\Dispatcher.cs:line 735
   at Mappy.Services.Dispatcher.OpenMap(string filename) in C:\projects\mappy\Mappy\Services\Dispatcher.cs:line 679
   at Mappy.Services.Dispatcher.Open() in C:\projects\mappy\Mappy\Services\Dispatcher.cs:line 218
   at Mappy.Models.MainFormViewModel.OpenMenuItemClick() in C:\projects\mappy\Mappy\Models\MainFormViewModel.cs:line 185
   at Mappy.UI.Forms.MainForm.OpenMenuItemClick(object sender, EventArgs e) in C:\projects\mappy\Mappy\UI\Forms\MainForm.cs:line 92
   at System.Windows.Forms.ToolStripItem.RaiseEvent(object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(ref Message m, MouseButtons button, int clicks)
   at System.Windows.Forms.Control.WndProc(ref Message m)
   at System.Windows.Forms.ScrollableControl.WndProc(ref Message m)
   at System.Windows.Forms.ToolStrip.WndProc(ref Message m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(ref Message m)
   at System.Windows.Forms.Control+ControlNativeWindow.OnMessage(ref Message m)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(ref Message m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, int msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(ref MSG msg)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, int reason, int pvLoopData)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(int reason, ApplicationContext context)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(int reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Mappy.Program.Main() in C:\projects\mappy\Mappy\Program.cs:line 79
```

**Comment by MHeasell** [comment]
This was a bug in TAUtil's HPI loading code, see https://github.com/MHeasell/TAUtil/issues/1

Fixed by pulling in new TAUtil in ab1bba6e4f532eb473b96ec2527f34af6d5859b3
